# Generated by Django 5.2.2 on 2025-06-09 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='スコア（正解数）')),
                ('points_earned', models.PositiveSmallIntegerField(default=0, verbose_name='獲得ポイント')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'クイズセッション',
                'verbose_name_plural': 'クイズセッション',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='小学1年生レベルの問題文', verbose_name='問題文')),
                ('choices', models.JSONField(default=list, help_text='5つの選択肢のリスト', verbose_name='選択肢')),
                ('correct_idx', models.PositiveSmallIntegerField(help_text='正解の選択肢のインデックス（0-4）', verbose_name='正解のインデックス')),
                ('question_number', models.PositiveSmallIntegerField(help_text='セッション内での問題番号（1-10）', verbose_name='問題番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
                'ordering': ['question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_idx', models.PositiveSmallIntegerField(help_text='ユーザーが選択した選択肢のインデックス（0-4）', verbose_name='選択した回答のインデックス')),
                ('is_correct', models.BooleanField(verbose_name='正解フラグ')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'unique_together': {('question',)},
            },
        ),
    ]
