# Generated by Django 4.2.7 on 2025-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreGeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="問題文")),
                ("choice_1", models.CharField(max_length=50, verbose_name="選択肢1")),
                ("choice_2", models.CharField(max_length=50, verbose_name="選択肢2")),
                ("choice_3", models.CharField(max_length=50, verbose_name="選択肢3")),
                (
                    "correct_answer",
                    models.IntegerField(
                        choices=[(0, "A"), (1, "B"), (2, "C")], verbose_name="正解"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(default=0, verbose_name="品質スコア"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("animals", "動物"),
                            ("sounds", "音・擬音語"),
                            ("opposites", "反対語"),
                            ("colors", "色"),
                            ("hiragana", "ひらがな"),
                            ("basic", "基本語彙"),
                            ("others", "その他"),
                        ],
                        default="others",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("used_count", models.IntegerField(default=0, verbose_name="使用回数")),
                ("correct_rate", models.FloatField(default=0.0, verbose_name="正答率")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "事前生成問題",
                "verbose_name_plural": "事前生成問題",
                "ordering": ["-quality_score", "-created_at"],
            },
        ),
    ]
