# Generated by Django 4.2.7 on 2025-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_pregeneratedquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="numeric_answer",
            field=models.IntegerField(
                blank=True,
                help_text="ユーザーが入力した数値（数値入力問題の場合）",
                null=True,
                verbose_name="数値回答",
            ),
        ),
        migrations.AddField(
            model_name="pregeneratedquestion",
            name="answer_format",
            field=models.CharField(
                choices=[("multiple_choice", "選択問題"), ("numeric", "数値入力")],
                default="multiple_choice",
                max_length=20,
                verbose_name="回答形式",
            ),
        ),
        migrations.AddField(
            model_name="pregeneratedquestion",
            name="correct_value",
            field=models.IntegerField(blank=True, null=True, verbose_name="正解の数値"),
        ),
        migrations.AddField(
            model_name="pregeneratedquestion",
            name="question_type",
            field=models.CharField(
                choices=[("language", "国語"), ("math", "算数")],
                default="language",
                max_length=20,
                verbose_name="問題タイプ",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_format",
            field=models.CharField(
                choices=[("multiple_choice", "選択問題"), ("numeric", "数値入力")],
                default="multiple_choice",
                max_length=20,
                verbose_name="回答形式",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_value",
            field=models.IntegerField(
                blank=True,
                help_text="正解の数値（数値入力問題の場合）",
                null=True,
                verbose_name="正解の数値",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("language", "国語"), ("math", "算数")],
                default="language",
                max_length=20,
                verbose_name="問題タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="selected_idx",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="ユーザーが選択した選択肢のインデックス（選択問題の場合）",
                null=True,
                verbose_name="選択した回答のインデックス",
            ),
        ),
        migrations.AlterField(
            model_name="pregeneratedquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("animals", "動物"),
                    ("sounds", "音・擬音語"),
                    ("opposites", "反対語"),
                    ("colors", "色"),
                    ("hiragana", "ひらがな"),
                    ("basic", "基本語彙"),
                    ("addition", "足し算"),
                    ("subtraction", "引き算"),
                    ("numbers", "数字"),
                    ("counting", "数え方"),
                    ("others", "その他"),
                ],
                default="others",
                max_length=20,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AlterField(
            model_name="pregeneratedquestion",
            name="choice_1",
            field=models.CharField(blank=True, max_length=50, verbose_name="選択肢1"),
        ),
        migrations.AlterField(
            model_name="pregeneratedquestion",
            name="choice_2",
            field=models.CharField(blank=True, max_length=50, verbose_name="選択肢2"),
        ),
        migrations.AlterField(
            model_name="pregeneratedquestion",
            name="choice_3",
            field=models.CharField(blank=True, max_length=50, verbose_name="選択肢3"),
        ),
        migrations.AlterField(
            model_name="pregeneratedquestion",
            name="correct_answer",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "A"), (1, "B"), (2, "C")],
                null=True,
                verbose_name="正解インデックス",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="選択肢のリスト（選択問題の場合）",
                verbose_name="選択肢",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_idx",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="正解の選択肢のインデックス（選択問題の場合）",
                null=True,
                verbose_name="正解のインデックス",
            ),
        ),
    ]
