# Generated by Django 4.2.7 on 2025-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "バッジ",
                "verbose_name_plural": "バッジ",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="badges_earned",
            field=models.JSONField(
                default=list,
                help_text="獲得したバッジのリスト",
                verbose_name="獲得バッジリスト",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="consecutive_days",
            field=models.PositiveIntegerField(
                default=0, help_text="連続で学習した日数", verbose_name="連続学習日数"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_points",
            field=models.PositiveIntegerField(
                default=0, help_text="レベルアップ用の経験値", verbose_name="経験値"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_study_date",
            field=models.DateField(
                blank=True,
                help_text="最後に学習した日付",
                null=True,
                verbose_name="最終学習日",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveIntegerField(
                default=1, help_text="現在のユーザーレベル", verbose_name="レベル"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="perfect_scores",
            field=models.PositiveIntegerField(
                default=0, help_text="満点を取った回数", verbose_name="満点回数"
            ),
        ),
    ]
